### ISSUE TITLE
Mixed Fragment crash

### ISSUE THREAD

**Issue by Tokoshoran** [MyM-ModpackTeam/ThaumicSkies#9] opened 2015-12-12 16:49 UTC
Every time I grow the Rosa Mysteria to stage 4 (Which seems to be fully grown), I harvest it for a mixed fragment, plant it back down, and am left with the purple fragment. It says right click for research, but attempting to do so boots me from the server with the message "Internal Server Error"

**Comment by chuggafan** [comment] 2015-12-12 17:03
KNOWN bug, we KNOW, you click it, with 2 of them, do NOT finish the stack, i'm doing this here to keep this DOCUMENTED

**Comment by Bennyboy1695** [comment] 2015-12-12 20:26
Duplicate of #3

**Closed as completed by Bennyboy1695** 2015-12-12 20:26 UTC
Labels: duplicate
